// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziqzjqglhdpepywzvdii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppcXpqcWdsaGRwZXB5d3p2ZGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjE4MjUsImV4cCI6MjA2MjQzNzgyNX0.WY61_ubhV7Zuhd8_TMpQGU4Eo73a2l4_I2_MJU1gvMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);